# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0004_auto_20180411_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Твит')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twit', to='images.Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_twit', to=settings.AUTH_USER_MODEL, verbose_name='Ценитель')),
            ],
            options={
                'verbose_name': 'Твит',
                'verbose_name_plural': 'Твиты',
                'ordering': ('date_added',),
            },
        ),
    ]
